os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode8
install:
  git clone --depth 1 https://github.com/kylef/swiftenv.git ~/.swiftenv
  export SWIFTENV_ROOT="$HOME/.swiftenv"
  export PATH="$SWIFTENV_ROOT/bin:$SWIFTENV_ROOT/shims:$PATH"
  swiftenv install
script:
  - swift build 
  - swift build -c release
